# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

jobs:
  include:
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: focal
    - php: 8.0
      dist: focal
    - php: 8.1
      dist: focal
    - php: 8.2
      dist: focal
      before_install:
      - "php `which composer` self-update"
      - "php `which composer` update --dev"

before_install:
  - composer update --dev

script:
  - cd test && ../vendor/bin/run_unit_tests
